### ISSUE TITLE
The address is not registered in the delivery handle registry and some delivery callbacks are ignored.

### ISSUE THREAD

**Issue by Adithya-copart** [karafka/rdkafka-ruby#131]
https://github.com/appsignal/rdkafka-ruby/blob/16a4497f59f4d369ebfb4ad0784161400fd96424/lib/rdkafka/bindings.rb#L253-L263

Using a mutex solves the problem but there is no concurrent access to the registry that I could find. Needs investigation.

**Comment by Adithya-copart** [comment]
**Reproduction Steps:**

1. Add a else statement to track the callbacks ignored silently.
2. Produce a large number of messages from the same producer.

```
def rdkafka_config(config_overrides={})
  config = {
    :"api.version.request" => false,
    :"broker.version.fallback" => "1.0",
    :"bootstrap.servers" => "localhost:9092",
    :"group.id" => "test_group",
    # :"auto.offset.reset" => "earliest",
    :"enable.partition.eof" => false,
    :"enable.auto.commit" => false,
    # :debug => "broker,topic,msg,cgrp,fetch"
  }
  config.merge!(config_overrides)
  Rdkafka::Config.new(config)
end


producer = rdkafka_config.producer

produced_offsets = []

producer.delivery_callback = lambda do |report|
  produced_offsets << [report.partition, report.offset]
end

handles = []

producer_thread = Thread.new do
  100_000.times do
    handles << producer.produce(
      topic:   "partitioner_test_topic",
      payload: "payload",
    )
  end
end

producer_thread.join
```

**Comment by mensfeld** [comment]
@Adithya-copart is it still an issue?

**Comment by adi-pen** [comment]
@mensfeld No, this can be closed.

This was not an issue that I noticed in a production environment or with real traffic. It was an observation while writing some test scripts IIRC.

Since there are no other reports apart from mine, I think this can be closed.

**Comment by mensfeld** [comment]
@adi-pen thanks! I will give it one more shot to replicate and if won't be able will close :pray:
