### ISSUE TITLE
Add Functionality to Reset the Offset of a Consumer Group

### ISSUE THREAD

**Issue by clewark-mdsol** [karafka/rdkafka-ruby#259]
Add Functionality to Reset the Offset of a Consumer Group

Like if I want my consumer group to reprocess the history of topic(s).

Like using Apache's Java CLI client, I think it would be this (below), but it would be nice to do it from the same Ruby codebase that is using this gem.

```
bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092  --group my-console-client  --topic keep-up-with-topic  --reset-offsets --to-earliest --execute
```

**Comment by mensfeld** [comment]
@clewark-mdsol this can be exceuted only when CG is not active right? If so, what prevents you from moving back in a CG and storing any offset you want?

I do agree though we may want to have admin API for that ;)

**Comment by mensfeld** [comment]
This is already doable the way I described above and a high level API for this is already in `Karafka::Admin`: https://karafka.io/docs/Admin-API/#changing-an-offset-of-a-consumer-group
