### ISSUE TITLE
Upgrade confluent kafka for CI

### ISSUE THREAD

**Issue by mensfeld** [karafka/rdkafka-ruby#285]
At least to `6.2.5`.

@thijsc any reason I am not aware not to?

**Comment by thijsc** [comment]
Should be fine!

**Comment by mensfeld** [comment]
It does behave slightly different (first data poll rarely yields one message which was standard previously) but aside from that it operates the same.

**Comment by mensfeld** [comment]
minor changes in the API messages + some small things in specs required to switch to newer kafka with kraft. :) work in progress

**Comment by mensfeld** [comment]
Note to self: once this is done, we could bump to new librdkafka
