### ISSUE TITLE
Bindings for create and delete groups

### ISSUE THREAD

**Issue by piotaixr** [karafka/rdkafka-ruby#341]
Hi,

In my current job, we have the need for the ability to manipulate consumer groups in a kafka cluster (mainly deleting them), and we had to implement the bindings for it. Are you ineterested in having this feature upstreamed?

If yes, I can try to do a PR for it for the end of next week :)
In the meantime, the implementation for the delete group is on my fork in a feature branch. It is currently missing mosts tests beacuse in order to test group deletion.... you need to be able to create them first and I haven't implementd this part yet :see_no_evil:

**Comment by mensfeld** [comment]
Yes please. I am slowly working on merging features and merging karafka-rdkafka and rdkafka-ruby into one. Such a feature would be highly appreciated.
