### ISSUE TITLE
rdkafka-ruby and librdkafka matrix

### ISSUE THREAD

**Issue by jychen7** [karafka/rdkafka-ruby#394]
### Background

When a developer finds a new feature or bug fix from `librdkafka`, it is a common need to fast check what minimal version of `rdkafka-ruby` is required to upgrade to.

e.g. I would like to quickly know what minimal `rdkafka-ruby` version uses `librdkafka >= 2.3.0`, in order to adopt the fix for "During offset validation a permanent error like host resolution failure would cause an offset reset. This isn't what's expected or what the Java implementation does. Solved by retrying even in case of permanent errors".

### Current
developer goes to changelog or source code of `rdkafka-ruby` and searches what `librdkafka` version is using for each release

### Proposal

Add a matrix to README or any document / wiki in the repo. What do you think ❓ 

e.g.
| rdkafka-ruby | librdkafka |
|-|-|
| 0.15.0 (2023-12-03) | 2.3.0 (2023-10-25) |
| 0.14.0 (2023-11-21) | 2.2.0 (2023-07-12) |
| 0.13.0 (2023-07-24) | 2.0.2 (2023-01-20) |
| 0.12.0 (2022-06-17) | 1.9.0 (2022-06-16) |
| 0.11.0 (2021-11-17) | 1.8.2 (2021-10-18) |
| 0.10.0 (2021-09-07) | 1.5.0 (2020-07-20) |

**Comment by mensfeld** [comment]
Great idea :)

**Comment by mensfeld** [comment]
@jychen7 do you want to PR?

**Comment by jychen7** [comment]
does updating README sounds good to you?
https://github.com/karafka/rdkafka-ruby/pull/396

**Comment by mensfeld** [comment]
@jychen7 thank you.
