### ISSUE TITLE
Post-fork initialization crash due to libcurl dynamic load from a fork

### ISSUE THREAD

**Issue by mensfeld** [karafka/rdkafka-ruby#398]
When running a Rails application with Rdkafka and Puma on macOS, creation of new rdkafka instance can cause crashes with an error related to fork() and Objective-C initialization. This is especially prevalent in Puma's clustered mode.

```
objc[<pid>]: +[NSCharacterSet initialize]
may have been in progress in another thread when fork() was called.
We cannot safely call it or ignore it in the fork() child process.
Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

the explanation and mitigation is here: https://karafka.io/docs/FAQ/#why-am-i-getting-nscharacterset-initialize-may-have-been-in-progress-in-another-thread-when-fork-error-when-forking-on-macos

as of now, I do not see any option to dynamically load libcurl on require, as today it is about libcurl, and tomorrow it may be about libssl.

I will open a specific issue in librdkafka to suggest exposure of `rd_kafka_global_init` which is currently not part of the API.

ref https://github.com/rails/rails/issues/38560

**Comment by mensfeld** [comment]
ref2: https://github.com/rails/rails/issues/38560

**Comment by mensfeld** [comment]
Closing. I covered this in karafka docs, there is no way except exposing `rd_kafka_global_init` ourselves which I do not want to do because I don't want to maintain a fork of `librdkafka`. confluentinc stance is pretty clear on that one as well.

**Comment by jasoncodes** [comment]
FYI I’ve worked around this with the following in an Rails initializer:

```ruby
Rdkafka::Config.with(logger: Logger.new(IO::NULL)) do                  
  Rdkafka::Config.new('test.mock.num.brokers' => 1).admin.close
end
```

This starts up and closes an admin client in test mode. Test mode does not make any an external connections and temporarily replacing the logger prevents the “Mock cluster” message being outputted.

Note: the above code uses `active_support/core_ext/object/with` to temporarily change the logger.

**Comment by mensfeld** [comment]
Yeah I did mention this in the karafka docs but I'm not sure if this is a stable enough solution, thus I was hesitant to incorporate it out of the box. Nonetheless if you say it works maybe worth adding.
