### ISSUE TITLE
404 librdkafka not found incident / FIXED

### ISSUE THREAD

**Issue by mensfeld** [karafka/rdkafka-ruby#465]
https://github.com/confluentinc/librdkafka/releases/tag/v2.5.0

**Comment by spajic** [comment]
@mensfeld this URL returns 404 for me

https://github.com/confluentinc/librdkafka/releases/tag/v2.4.0 returns 404 too

And because of that I can't install `rdkafka-ruby` gem now

<img width="960" alt="Screenshot 2024-07-10 at 18 46 48" src="https://github.com/karafka/rdkafka-ruby/assets/498924/be7c4434-68e9-4832-a644-bba5ed677594">

**Comment by ecbrodie** [comment]
If we somehow have the latest tarball from `librdkafka` stored somewhere ([seems to be downloaded here](https://github.com/karafka/rdkafka-ruby/blob/a073865fc73dffdabed89815288f5b327e3b673c/ext/Rakefile#L26)), maybe could we temporarily vendor that tarball into this repo and then allow the maintainers of this gem to explore a more permanent approach?

**Comment by mensfeld** [comment]
@ecbrodie it's already being worked on.

**Comment by mensfeld** [comment]
JUST PLEASE GIVE ME SOME TIME.

**Comment by lfrancke** [comment]
I tried reaching out to a few people at Confluent and asked in the ASF Slack #kafka  Channel.
I am going to assume that this just vanishing from "the Internet" is a mistake and/or temporary.

Maybe there was a security issue in the latest release so they had to pull it.

**Comment by mensfeld** [comment]
Yeah, that may be. Though I had planned to move this to offline a while ago already (there's a card for this for a while). I AM WORKING HARD TO FIX THIS!

**Comment by mensfeld** [comment]
Ok compiling with local source...

**Comment by mensfeld** [comment]
https://github.com/karafka/karafka-rdkafka has been released with 2.4.0 librdkafka. I am now backporting it to rdkafka + older versoins.

**Comment by mensfeld** [comment]
PR is running in the CI. Once green, will merge and start releasing backports.

**Comment by mensfeld** [comment]
Merged. Preparing 0.16.1 release...

**Comment by mensfeld** [comment]
0.16.1 of rdkafka has been released: https://rubygems.org/gems/rdkafka

Please `bundle update karafka-rdkafka` OR `bundle update rdkafka` depending on which one you use.

I will be backporting older versions soon. If you value my work, please convince your business to support me, so I can support you when something like this happens again ;)

**Comment by mensfeld** [comment]
Ok. Backporting karafka-rdkafka. Once that is done, I will backport 0.15 and 0.14 at least.

**Comment by rafer** [comment]
Thank you so much. +1 for a `0.13` backport (running zendesk/racecar `2.10` which depends on librdkafka `~> 0.13.0`).

**Comment by vrmontes** [comment]
Thanks! a `0.13` backport would be greatly appreciated

**Comment by rsanheim** [comment]
Thanks for your quick work here @mensfeld !

**Comment by mensfeld** [comment]
closing https://github.com/karafka/rdkafka-ruby/issues/384 which foresaw this incident.

**Comment by Senjai** [comment]
@mensfeld We're hard locked to 0.15.1, I copied this backport here but for librdkafka 2.3.0, same sha, here is the fork https://github.com/Senjai/rdkafka-ruby, HEAD is 0.15.1 if you want me to PR it somehow or cherry pick

**Comment by mensfeld** [comment]
@Senjai I don't need a fork. I have a plan and I am working on it. It just takes time.

**Comment by ankit-tangoe** [comment]
@mensfeld A backport of version 0.8.1 would be greatly appreciated. Thank you!

**Comment by mensfeld** [comment]
@ankit-tangoe no. Since confluent restored the repo, I will release only:

- [ ] 0.15.2
- [ ] 0.14.1
- [ ] 0.13.1
- [ ] 0.12.1

everything else will stay as it is.

**Comment by mensfeld** [comment]
Ok closing this issue. I will backport 0.12 - 0.14 without a rush since both 015 and 0.16 has been released.

Once again: if you rely on my work, please consider supporting me.

**Comment by mensfeld** [comment]
013 and 012 will be backported tomorrow. From now on all releases will be fully rubygems dependent. no more GH reliance.

**Comment by mensfeld** [comment]
All planned backports has been released. No more GH dependence for rdkafka in the future.

**Comment by mensfeld** [comment]
postmortem: https://mensfeld.pl/2024/07/the-librdkafka-supply-chain-breakdown-rdkafka-rubys-darkest-hour/
