### ISSUE TITLE
Failed with error 126: The specified module could not be found.\r (LoadError)

### ISSUE THREAD

**Issue by altheampf-bread** [karafka/rdkafka-ruby#492]
Seeing this error during Run Time,
load_library': Could not open library 'C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rdkafka-0.17.0/lib/rdkafka/../../ext/librdkafka.so': Faile
d with error 126: The specified module could not be found.\r (LoadError)

Need assistance on this please.

**Comment by mensfeld** [comment]
This gem does not support windows. I do not have plans to support it unless I am sponsored to do so and/or someone is willing to provide this support with stable and working CI for future maintenance.

ref: https://github.com/karafka/rdkafka-ruby/issues/188

> If there is anyone willing to PR and work on adding Windows specs and all that is needed to have at least basic sanity checks, I would be happy to work with that person.
