### ISSUE TITLE
HOWTO: Subscribe to multiple topics

### ISSUE THREAD

**Issue by magynhard** [karafka/rdkafka-ruby#520]
I did not find any information about subscribing to multiple topics at the same time.

If i create a consumer and `#subscribe()` to a topic and subscribe to another topic after, only the latest topic is subscribed to. I can see the last subscribed topic by `consumer#subscription`.

Do I need to create a separate consumer for each topic or is there another way?

Hope you can add the answer to the README documentation as well.

**Comment by mensfeld** [comment]
Hey, @magynhard, this is a low-level binding layer for which I do not provide extensive docs. I highly recommend using our other OSS: https://github.com/karafka/karafka/ to consume data. It supports multi-topic subscriptions.

But to answer your question: https://karafka.io/docs/code/rdkafka-ruby/Rdkafka/Consumer.html#subscribe-instance_method

it accepts a list of topics.
